port: 3000
supported_events_actions:
  pull_request:
    - assigned
    - closed
    - edited
    - opened
    - ready_for_review
    - reopened
    - review_requested
  pull_request_review:
    - dismissed
    - edited
    - submitted
  pull_request_review_comment:
    - created
  pull_request_review_thread: null # ignore all events
